spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/food_delivery
    username: root
    password: java19foodapp
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
server:
  servlet:
    context-path: /api
file:
  upload-dir: 'C:\Users\Admin\Documents\Cybersoft Java 19\Food Delivery\Uploads'
